server:
  port: 8083
  context-path: /common_mapper
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: cja
mybatis:
  type-aliases-package: com.baizhi.entity